config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'home#index'
  
  post '/attemptcheckout' => 'home#attemptcheckout'
  post '/addtocart' => 'home#addtocart'
  post '/removefromcart' => 'home#removefromcart'
  
  post '/checkout' => 'home#checkout'
  post '/orderhistory' => 'home#orderhistory'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :User

  class << self # Class methods
    def addItem (cart_id, item_id, item_qty)
    	item = Item.find(item_id)
    	if item.stock < item_qty
    		return -1
    	end

    	cart_item = CartItem.where(Cart_id: cart_id, Item_id: item_id)
		if cart_item.blank?
			CartItem.create(Cart_id: cart_id, Item_id: item_id, price: item.price, quantity: item_qty)
		else
			cart_item.first().update(quantity: cart_item.first().quantity+item_qty)
		end

		item.update(stock: item.stock - item_qty)
		return 1
  	end

  	def removeItem (cart_item_id)
  		cart_item = CartItem.where(id: cart_item_id)
		if !cart_item.blank?
			item = Item.find(cart_item.first().Item_id)
			item.update(stock: item.stock + cart_item.first().quantity)
			cart_item.first().destroy
		end
	end

	def checkout (cart_id)
		cart = Cart.find(cart_id)
		tp = totalPrice(cart_id)
		cart.update(total: tp)
		cart.update(checkout_date: DateTime.now)
		return 1
	end

	def orderhistory(user_id)
		carts = Cart.where(User_id: user_id).where.not(checkout_date: nil)
		orderhistory = []
		(0..carts.size-1).each do |i|

			cart_items = CartItem.where(Cart_id: carts[i].id).to_a
			items = []
			cart_items.each do |ci|
				item_instance = Item.find(ci.Item_id)

				item = []
				item << item_instance.name
				item << item_instance.price
				item << ci.quantity

				items << item
			end


			order_instance = []
			order_instance << items
			order_instance << carts[i].checkout_date
			order_instance << carts[i].total

			orderhistory << order_instance
		end
		return orderhistory
	end

	def empty? (cart_id)
		return CartItem.where(Cart_id: cart_id).to_a.blank?
	end

	def totalPrice (cart_id)
		cart_items = CartItem.where(Cart_id: cart_id)
		total = 0
		cart_items.each do |c|
			total += c.price*c.quantity
		end
		return total
	end
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :Item
  belongs_to :Cart
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
	def index
		refreshcurrentcart
		refresh
	end

	def attemptcheckout
		if !Cart.empty?(current_user.Cart_id)
			refreshcartitems
			render 'app/views/home/checkout.html.erb'
			return
		end
		refreshcurrentcart
		refresh
	end

	def addtocart
		value = Cart.addItem(current_user.Cart_id, params[:item_id], params[:item_qty].to_i)
		if value == -1
			@items_list = Item.all();
			refreshcartitems
			flash.now[:alert] = "Out of stock!"
			render 'app/views/home/index.html.erb'
			return
		end
		refresh
	end

	def removefromcart
		Cart.removeItem(params[:cart_item_id])
		refresh
	end

	def checkout
		if !Cart.empty?(current_user.Cart_id)
			value = Cart.checkout(current_user.Cart_id)
			if value == -1
				@items_list = Item.all();
				refreshcartitems
				flash.now[:alert] = "Some items in your cart were already out of stock by the time you checked out! Cart cleared of items that are out of stock."
				render 'app/views/home/index.html.erb'
				return
			end
		end
		current_user.Cart_id = nil
		refreshcurrentcart
		flash.now[:notice] = "Checkout successful."
		refresh
	end

	def orderhistory
		o = Cart.orderhistory(current_user.id)
		if o != nil
			return o
		end
	end

	def refreshcartitems
		@cart_items = CartItem.where(Cart_id: current_user.Cart_id)
		@cart_list = []
		@cart_items.each do |c|
			item = Item.where(id: c.Item_id)
			@cart_list << item.first()
		end
	end

	def refreshcurrentcart
		if current_user.Cart_id==nil
			@current_cart = Cart.create(User_id:current_user.id)
			current_user.update(Cart_id:@current_cart.id)
		else
			@current_cart = Cart.find(current_user.Cart_id)
		end
	end

	def refresh
		@items_list = Item.all();
		refreshcartitems
		render 'app/views/home/index.html.erb'
	end

	def get_cart_total_price
		if current_user.Cart_id!=nil
			return Cart.totalPrice(current_user.Cart_id)
		end
	end

	helper_method :get_cart_total_price, :orderhistory
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/checkout.html.erb
<div class="center hero-unit">
	<% if user_signed_in? %>
		<h2> Checkout </h2>

		<div align = "left" style="width:400px">
			<h4> Cart - Php<%= get_cart_total_price %></h4>
			<div>
				<% (0..@cart_list.size-1).each do |i| %>
					<%= @cart_list[i].name %> (Php<%= @cart_list[i].price %>, 
					<% if @cart_items[i].quantity > 1 %> 
						<%= @cart_items[i].quantity %> pieces
					<% else %>
						1 piece
					<% end %>
					)<br>
				<% end %>
			</div>


		</div> 
		<br><br>



			<%= form_tag url_for(:controller=>"home", :action => "checkout"), :method => "post" do %>
				<div class = "row">
					<div class = "col-sm-6">
						<%= field_set_tag 'Billing Information' do |f| %>
						  <p>First Name:     <%= text_field_tag 'firstname', nil, :required => true %></p>
						  <p>Last Name:      <%= text_field_tag 'lastname', nil, :required => true %></p>
						  <p>Company: <%= text_field_tag 'company', nil %></p>
						  <p>Email: <%= email_field_tag 'email', nil, :required => true %></p>
						  <p>Phone: <%= phone_field_tag 'phone', nil, :required => true %></p>
						  <br><br>
						  <p>Address: <%= text_field_tag 'address', nil, :required => true %></p>
						  <p>Address2: <%= text_field_tag 'address2', nil, :required => true %></p>
						  <p>City: <%= text_field_tag 'city', nil, :required => true %></p>
						  <p>Postal/ZIP Code: <%= text_field_tag 'postal', nil, :required => true %></p>
						  <p>Country: <%= country_select("", "") %></p>
						<% end %>
						<br>
					</div>
					<div class = "col-sm-6">
						<%= field_set_tag 'Credit Card Details' do |f| %>
						  <p>Card type:      <%= select_tag "Cart type", "<option>VISA</option><option>MasterCard</option><option>AMEX</option>".html_safe %> </p>
						  <p>Card Number:     <%= text_field_tag 'firstname', nil, :required => true %></p>
						  <p>Expiration: <%= text_field_tag 'yy', nil, :size=>"2", :placeholder =>"YY", :required => true %> / <%= text_field_tag 'mm', nil, :size=>"2", :placeholder =>"MM" , :required => true %></p>
						  <p>CVV: <%= text_field_tag 'company', nil, :required => true %></p>
						  <% end %>
						  <br>
					<%= field_set_tag 'Special Offer!' do |f| %>
						<label> Get 100% off by typing the super secret code: givecamilleanA</label>
						  <p>Special Code: <%= text_field_tag 'special code', nil%></p>
					<% end %>
					</div>
				</div>
					<%= submit_tag 'Checkout', class: "btn btn-default" %> 
			<% end %>

	<% end %>
</div>

app/views/home/index.html.erb
<div class="center hero-unit">
	<% if user_signed_in? %>
		<div>
			<h2> <i>Articles Philosophiques</i>: Philosophical Items </h2>
			<div id="owl-demo" class="owl-carousel owl-theme">
				<% @items_list.each do |item| %>
					<div class = "item link row" id = "<%= 'itemdisplay' + item.id.to_s %>">
						<div class = "col-sm-4" style = "margin-top:10px">
							<img src="<%= image_path( item.image_path ) %>" style="width:160px;height:160px">
							<p align = "center"> [ Stock: <%= item.stock %> ]</p>
						</div>
						<div class = "col-sm-8">
							<br>
							<%= form_tag url_for(:controller=>"home", :action => "addtocart"), :method => "post" do %>
									
									<%= hidden_field_tag :item_id,  item.id %>
									<% if item.stock > 0 %>
										<%= number_field_tag :item_qty, 1, min:1, max:item.stock, step:1, style: "color:#000" %> 
										<%= submit_tag 'Add to Cart', class: "btn btn-default" %>
									<% else %>
										<%= submit_tag 'No Stock', class: "btn btn-default", disabled: true %>
									<% end %>
							<% end %><br>
							<h4><%= item.name %></h4>
							<p>Php<%= item.price %><br><%=item.description%> </p>
							<br>
						</div>
					</div>
				<% end %>
			</div>
		<div>
		<br>
		<div>
			<h2><i>Le Chariot</i>: Cart
				<% if @cart_list.size > 0 %>
					<%= form_tag url_for(:controller=>"home", :action => "attemptcheckout"), :method => "post" do %>
						<%= submit_tag 'Checkout', class: "btn btn-default" %>
					<% end %>
				<% end %>
			</h2>

			<% if @cart_list.size == 0 %>
				<label> Cart is empty </label>
			<% else %>
				<label> Total: Php <%= get_cart_total_price %> </label>
				<div id="owl-demo2" class="owl-carousel owl-theme">
					<% (0..@cart_list.size-1).each do |i| %>
						<div class = "item link">
							<h4> <%= @cart_list[i].name %> (Php<%= @cart_list[i].price %>)</h4>
							<% if @cart_items[i].quantity > 1 %> 
								<%= @cart_items[i].quantity %> pieces
							<% else %>
								1 piece
							<% end %><br><br>
							<%= form_tag url_for(:controller=>"home", :action => "removefromcart"), :method => "post" do %>
									<%= hidden_field_tag :cart_item_id,  @cart_items[i].id %>
									<%= submit_tag 'Remove From Cart', class: "btn btn-default" %> 
							<% end %>
						</div>
					<% end %>
				</div>
			<% end %>

		<div>
		
	<% end %>
</div>

app/views/home/orderhistory.html.erb
<div class="center hero-unit">
	<% if user_signed_in? %>
		<h3>Order History</h3>
		<div align = "left" style="width:400px">
			<% (0..orderhistory.size-1).each do |x| %>
				<h4 align = "center"> <%= x+1 %>: <%= orderhistory[x][1] %> [Total: Php<%= orderhistory[x][2] %>]</h4>
					<% items = orderhistory[x][0] %>
					<% items.each do |item| %>
						<%= item[0] %> (Php<%= item[1] %>, <%= item[2] %>)
						<br>
					<% end %>
				<div>
					
				</div>
				<br>
			<% end %>
		</div> 

	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>René des Cart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav id="navigation" class="navbar navbar-default navbar-fixed-top">
	  <div class="container">
	    <div class="navbar-header">
	      <%= link_to 'René des Cart', root_url, class: 'navbar-brand' %>
	    </div>
	       <ul class="nav navbar-nav navbar-right">
	       	
		      <% if user_signed_in? %>
		      	 <li> <div class="navbar-name"> <%= current_user.email %> </div></li>
		      	 <li><%= link_to 'Order History', orderhistory_path, :method => "post" %> </li>
		      	 <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
		      <% end %>
		    </ul>
	</nav>

	<div class="container">
		<br>
		<% if notice %>
	      <p class="alert alert-success"><%= notice %></p>
	    <% end %>
	    <% if alert %>
	      <p class="alert alert-danger"><%= alert %></p>
	    <% end %>
		<%= yield %>
	</div>
</body>
</html>